resources:
  - name: go_gitRepo_demo
    type: GitRepo
    configuration:
      path: eladh/pipeline
      gitProvider: git

pipelines:
  - name: service
    steps:
      - name: demo_step
        type: Bash
        execution:
          onStart:
            - ls -lh
