resources:
  - name: go_gitRepo_demo
    type: GitRepo
    configuration:
      path: eladh/pipeline
      gitProvider: git

pipelines:
  - name: service
    steps:
      - name: demo_step1
        type: Bash
        execution:
          onStart:
            - ls -lh
      - name: demo_step2
        type: Bash
        configuration:
          inputSteps:
            - name: demo_step1
        execution:
          onStart:
            - dir
